In [24]:
#Exercise 1 Stack
myStack=['a','b','c']

def stackAppend(option):
    myStack.append('d')
    print(myStack)

def stackPop(option):
    myStack.pop()
    print(myStack)

def stackView(option):
    myStack.copy()
    print(myStack)
    
def stackPeek(option):
    myStack.peek()
    print(myStack)

option = input ("Select an option")

while option !="exit":
    if option =="Push":
        stackAppend(option) 
    
    elif option =="Pop":
         stackPop(option)
    
    elif option == "View":
        stackView(option)
        
    else :
        print ("Invalid Option selected!Try Again")
    
    option = input("Select an Option")

Select an optionPush
['a', 'b', 'c', 'd']
Select an OptionPop
['a', 'b', 'c']
Select an OptionView
['a', 'b', 'c']
Select an Optionview
Invalid Option selected!Try Again
Select an Optionpeek
Invalid Option selected!Try Again
Select an OptionPush
['a', 'b', 'c', 'd']
Select an Optionexit

In [28]:
#Exercise 1 Queue

myQueue = ['a','b','e']

def queueEnqueue(option):
    myQueue.append('c')
    print(myQueue)

def queueDequeue(option):
    myQueue.pop(0)
    print(myQueue)

def queueView(option):
    myQueue.copy()
    print(myQueue)

option=input("Select an Option")

while option !="exit":
    
    if option =="Enqueue":
        queueEnqueue(option)

    elif option == "Dequeue":
        queueDequeue(option)
    
    elif option == "View":
         queueView(option)
    
    else :
        print("Invalid Option Entered!Try Again")
    
    option=input("Select an Option")

Select an OptionView
['a', 'b', 'e']
Select an OptionEnqueue
['a', 'b', 'e', 'c']
Select an OptionDequeue
['b', 'e', 'c']
Select an Optionexit

In [161]:
april18 = {1: {'L3': 390},2 :{'P2': 250}, 3:{'N6':460} , 4:{'B8': 470}}
may18  = {1: {'L3': 345},2 :{'P2': 270}, 3:{'N6':480} , 4:{'B8': 510}}
june18  = {1: {'L3': 379},2 :{'P2': 300}, 3:{'N6':450} , 4:{'B8': 360}}



def salesReport():

            london1 = april18[1]['L3']
            london2 = may18[1]['L3']
            london3 = june18[1]['L3']
            londonTotal = london1 + london2 + london3
            londonAverage = round ((londonTotal) / 3 ,2)
            
            #Paris Details
            paris1 = april18[2]['P2']
            paris2 = may18[2]['P2']
            paris3 = june18[2]['P2']
            parisTotal = paris1 + paris2 + paris3
            parisAverage = round((parisTotal)/3 , 2)
            
            #New York Details
            newyork1 = april18[3]['N6']
            newyork2 = may18[3]['N6']
            newyork3 = june18[3]['N6']
            newyorkTotal = newyork1 + newyork2 + newyork3
            newyorkAverage = round ((newyorkTotal) / 3 , 2)
            
            #Beijing Details
            beijing1 = april18[4]['B8']
            beijing2 = may18[4]['B8']
            beijing3 = june18[4]['B8']
            beijingTotal = beijing1 + beijing2 +beijing3
            beijingAverage = round((beijingTotal) / 3 ,2)
            
            
            #April Details
            april18Total = london1 + paris1 + newyork1 + beijing1
            april18Average = round ((april18Total) / 3,2)
            
            #May Details
            may18Total = london2 + paris2 + newyork2 + beijing2
            may18Average = round ((may18Total) / 3,2)
            
            
            #June Details
            june18Total = london3 + paris3 + newyork3 + beijing3
            june18Average = round ((june18Total) / 3,2)
            
            #GrandTotal
            grandTotal = april18Total + may18Total +june18Total

            print ("Quaterly sales report")
            print()
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("London","L3:" , londonAverage,londonTotal ))
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("Paris","P2:" , parisAverage,parisTotal ))
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("New York","N6:" , newyorkAverage,newyorkTotal ))
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("Beijing","B3:" , beijingAverage,beijingTotal ))
            print()
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("April",":" , april18Average,april18Total ))
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("May",":" , may18Average,may18Total ))
            print ('{:10s} {:>4s}{:12.2f}{:>12d}'.format("June",":" , june18Average,june18Total ))
            print()
            print ('{:2s} {:>1s}{:5d}'.format("Total",":" , grandTotal ))

salesReport()

Quaterly sales report

London      L3:      371.33        1114
Paris       P2:      273.33         820
New York    N6:      463.33        1390
Beijing     B3:      446.67        1340

April         :      523.33        1570
May           :      535.00        1605
June          :      496.33        1489

Total : 4664